// Liste des secteurs de travail prédéfinis pour les chauffeurs
export const FRENCH_SECTORS = [
  // Île-de-France
  { id: "75", label: "Paris (75)" },
  { id: "77", label: "Seine-et-Marne (77)" },
  { id: "78", label: "Yvelines (78)" },
  { id: "91", label: "Essonne (91)" },
  { id: "92", label: "Hauts-de-Seine (92)" },
  { id: "93", label: "Seine-Saint-Denis (93)" },
  { id: "94", label: "Val-de-Marne (94)" },
  { id: "95", label: "Val-d'Oise (95)" },
  
  // Grandes villes et métropoles
  { id: "marseille", label: "Marseille" },
  { id: "lyon", label: "Lyon" },
  { id: "toulouse", label: "Toulouse" },
  { id: "nice", label: "Nice" },
  { id: "nantes", label: "Nantes" },
  { id: "strasbourg", label: "Strasbourg" },
  { id: "montpellier", label: "Montpellier" },
  { id: "bordeaux", label: "Bordeaux" },
  { id: "lille", label: "Lille" },
  { id: "rennes", label: "Rennes" },
  { id: "reims", label: "Reims" },
  { id: "toulon", label: "Toulon" },
  { id: "grenoble", label: "Grenoble" },
  { id: "dijon", label: "Dijon" },
  { id: "angers", label: "Angers" },
  { id: "nimes", label: "Nîmes" },
  { id: "saint-etienne", label: "Saint-Étienne" },
  { id: "clermont-ferrand", label: "Clermont-Ferrand" },
  { id: "tours", label: "Tours" },
  { id: "limoges", label: "Limoges" },
  { id: "orleans", label: "Orléans" },
  { id: "aix-en-provence", label: "Aix-en-Provence" },
  { id: "metz", label: "Metz" },
  { id: "besancon", label: "Besançon" },
  { id: "caen", label: "Caen" },
  { id: "mulhouse", label: "Mulhouse" },
  { id: "nancy", label: "Nancy" },
  { id: "rouen", label: "Rouen" },
  { id: "avignon", label: "Avignon" },
  
  // Autres départements populaires
  { id: "06", label: "Alpes-Maritimes (06)" },
  { id: "13", label: "Bouches-du-Rhône (13)" },
  { id: "31", label: "Haute-Garonne (31)" },
  { id: "33", label: "Gironde (33)" },
  { id: "34", label: "Hérault (34)" },
  { id: "35", label: "Ille-et-Vilaine (35)" },
  { id: "38", label: "Isère (38)" },
  { id: "44", label: "Loire-Atlantique (44)" },
  { id: "59", label: "Nord (59)" },
  { id: "62", label: "Pas-de-Calais (62)" },
  { id: "67", label: "Bas-Rhin (67)" },
  { id: "69", label: "Rhône (69)" },
  { id: "83", label: "Var (83)" },
].sort((a, b) => a.label.localeCompare(b.label));
