project_id = "iyothopplhbwcfrpxryc"

[functions.recreate-test-clients]
verify_jwt = false

[functions.qr-code-manager]
verify_jwt = false

[functions.register-client-qr]
verify_jwt = false

[functions.create-devis-auto]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-driver-validation-email]
verify_jwt = false

[functions.cleanup-old-messages]
verify_jwt = false

[functions.driver-assistant]
verify_jwt = true