// Configuration for the Guide du Chauffeur Indépendant
// Academy Hub URL — will be updated when the hub is ready
export const ACADEMY_HUB_URL = "https://solocabacademy.fr";

// Tool download formats
export type ToolFormat = "pdf" | "word" | "excel";

export interface ToolDefinition {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  formats: ToolFormat[];
  description: string;
  contentLines: string[]; // Lines to render in the PDF worksheet
  tableHeaders?: string[];
  tableRows?: number;
}

// The 18 tools organized by category
export const guideTools: ToolDefinition[] = [
  // === PILOTAGE FINANCIER ===
  {
    id: "calculateur-rentabilite",
    title: "Calculateur de Rentabilite",
    subtitle: "Connaissez votre vrai taux horaire",
    category: "PILOTAGE FINANCIER",
    formats: ["pdf", "excel"],
    description: "Calculez votre rentabilite reelle en integrant toutes les charges. Un outil essentiel pour prendre conscience de votre situation et mesurer vos progres.",
    tableHeaders: ["Poste", "Montant Journalier", "Montant Mensuel", "Montant Annuel"],
    tableRows: 12,
    contentLines: [
      "REVENUS",
      "Chiffre d'affaires brut plateformes : _____ EUR",
      "Chiffre d'affaires brut clients prives : _____ EUR",
      "Autres revenus : _____ EUR",
      "TOTAL REVENUS : _____ EUR",
      "",
      "CHARGES VARIABLES",
      "Commissions plateformes (___%) : _____ EUR",
      "Carburant / Recharge electrique : _____ EUR",
      "Peages : _____ EUR",
      "",
      "CHARGES FIXES",
      "Leasing / Credit vehicule : _____ EUR",
      "Assurance professionnelle : _____ EUR",
      "Cotisations URSSAF (___%) : _____ EUR",
      "Entretien vehicule (mensualise) : _____ EUR",
      "Telephone / Internet : _____ EUR",
      "Comptable : _____ EUR",
      "CFE / Impots : _____ EUR",
      "",
      "RESULTAT",
      "Total charges : _____ EUR",
      "Benefice net : _____ EUR",
      "Heures travaillees : _____ h",
      "TAUX HORAIRE REEL : _____ EUR/h",
    ],
  },
  {
    id: "tableau-bord-hebdo",
    title: "Tableau de Bord Hebdomadaire",
    subtitle: "Pilotez votre activite chaque semaine",
    category: "PILOTAGE FINANCIER",
    formats: ["pdf", "excel"],
    description: "Suivez vos indicateurs cles chaque semaine pour mesurer votre progression vers l'independance.",
    tableHeaders: ["Indicateur", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Sam", "Dim", "Total"],
    tableRows: 10,
    contentLines: [
      "ACTIVITE",
      "Nombre de courses plateformes : ___",
      "Nombre de courses privees : ___",
      "Ratio prive/total : ____%",
      "",
      "CHIFFRE D'AFFAIRES",
      "CA plateformes : _____ EUR",
      "CA clients prives : _____ EUR",
      "CA total : _____ EUR",
      "",
      "PROSPECTION",
      "Contacts inities : ___",
      "Rendez-vous obtenus : ___",
      "Nouveaux clients signes : ___",
      "",
      "OBJECTIF SEMAINE : _____ EUR",
      "RESULTAT : _____ EUR",
      "ECART : _____ EUR",
    ],
  },
  {
    id: "simulateur-objectifs",
    title: "Simulateur d'Objectifs de CA",
    subtitle: "Calculez combien de courses il vous faut",
    category: "PILOTAGE FINANCIER",
    formats: ["pdf", "excel"],
    description: "Partez de votre objectif de revenu et remontez jusqu'au nombre de courses necessaires. Un outil de planification inversee.",
    contentLines: [
      "MON OBJECTIF",
      "Revenu net mensuel souhaite : _____ EUR",
      "",
      "CALCUL INVERSE",
      "Charges fixes mensuelles : _____ EUR",
      "Taux de charges sociales : ____%",
      "CA brut necessaire : _____ EUR",
      "",
      "SCENARIO PLATEFORMES (commission ____%)",
      "CA brut apres commission : _____ EUR",
      "Panier moyen par course : _____ EUR",
      "Courses necessaires/mois : ___",
      "Courses necessaires/jour (___j/sem) : ___",
      "",
      "SCENARIO CLIENTELE PRIVEE (0% commission)",
      "CA brut necessaire : _____ EUR",
      "Panier moyen par course : _____ EUR",
      "Courses necessaires/mois : ___",
      "Courses necessaires/jour (___j/sem) : ___",
      "",
      "DIFFERENCE : ___ courses/jour en moins !",
      "TEMPS RECUPERE : ___ heures/semaine",
    ],
  },
  {
    id: "budget-previsionnel",
    title: "Budget Previsionnel Annuel",
    subtitle: "Anticipez votre annee financiere",
    category: "PILOTAGE FINANCIER",
    formats: ["pdf", "excel"],
    description: "Planifiez vos revenus et charges mois par mois pour securiser votre tresorerie et atteindre vos objectifs.",
    tableHeaders: ["Mois", "CA Prevu", "CA Reel", "Charges", "Benefice", "Tresorerie"],
    tableRows: 12,
    contentLines: [
      "Janvier : CA _____ | Charges _____ | Net _____",
      "Fevrier : CA _____ | Charges _____ | Net _____",
      "Mars : CA _____ | Charges _____ | Net _____",
      "Avril : CA _____ | Charges _____ | Net _____",
      "Mai : CA _____ | Charges _____ | Net _____",
      "Juin : CA _____ | Charges _____ | Net _____",
      "Juillet : CA _____ | Charges _____ | Net _____",
      "Aout : CA _____ | Charges _____ | Net _____",
      "Septembre : CA _____ | Charges _____ | Net _____",
      "Octobre : CA _____ | Charges _____ | Net _____",
      "Novembre : CA _____ | Charges _____ | Net _____",
      "Decembre : CA _____ | Charges _____ | Net _____",
      "",
      "TOTAL ANNUEL : CA _____ | Charges _____ | Net _____",
      "OBJECTIF ANNUEL : _____ EUR",
      "ECART : _____ EUR",
    ],
  },
  {
    id: "modele-facture",
    title: "Modele de Facture VTC",
    subtitle: "Facturez comme un professionnel",
    category: "PILOTAGE FINANCIER",
    formats: ["pdf", "word"],
    description: "Un modele de facture conforme aux obligations legales, pret a personnaliser avec vos coordonnees.",
    contentLines: [
      "[VOTRE NOM / RAISON SOCIALE]",
      "[Adresse complete]",
      "SIRET : _______________",
      "N. TVA : _______________",
      "",
      "FACTURE N. : F-2026-____",
      "Date : __ / __ / 2026",
      "",
      "CLIENT",
      "Nom : _________________________",
      "Adresse : _________________________",
      "",
      "PRESTATIONS",
      "Date | Trajet | Km | Prix HT",
      "_____|________|____|________",
      "_____|________|____|________",
      "_____|________|____|________",
      "",
      "Total HT : ________ EUR",
      "TVA (10%) : ________ EUR",
      "TOTAL TTC : ________ EUR",
      "",
      "Conditions : Paiement a reception",
      "Mode de paiement : Virement / CB / Especes",
      "IBAN : ___________________________",
    ],
  },

  // === GESTION CLIENTS ===
  {
    id: "fiche-suivi-clients",
    title: "Fiche Suivi Clients (CRM)",
    subtitle: "Gerez vos clients comme un pro",
    category: "GESTION CLIENTS",
    formats: ["pdf", "excel"],
    description: "Un mini-CRM papier pour suivre chaque client : coordonnees, preferences, historique et chiffre d'affaires genere.",
    tableHeaders: ["Nom", "Telephone", "Email", "Type", "Frequence", "CA Mensuel", "Notes"],
    tableRows: 15,
    contentLines: [
      "CLIENT N.___",
      "Nom : _________________________",
      "Telephone : _________________________",
      "Email : _________________________",
      "Adresse habituelle : _________________________",
      "Type : [ ] Particulier [ ] Entreprise [ ] Hotel [ ] Autre",
      "Frequence : [ ] Quotidien [ ] Hebdo [ ] Mensuel [ ] Ponctuel",
      "",
      "PREFERENCES",
      "Musique : [ ] Silence [ ] Classique [ ] Jazz [ ] Autre",
      "Temperature : [ ] Frais [ ] Tiede [ ] Chaud",
      "Conversation : [ ] Bavard [ ] Discret [ ] Selon humeur",
      "Eau : [ ] Plate [ ] Gazeuse [ ] Non",
      "Trajet prefere : _________________________",
      "",
      "HISTORIQUE (dernieres courses)",
      "Date | Trajet | Montant | Notes",
      "_____|________|_________|______",
      "",
      "CA total genere : _____ EUR",
      "Statut : [ ] VIP [ ] Regulier [ ] Occasionnel [ ] Prospect",
    ],
  },
  {
    id: "scorecard-satisfaction",
    title: "Scorecard Satisfaction Client",
    subtitle: "Evaluez et ameliorez votre service",
    category: "GESTION CLIENTS",
    formats: ["pdf", "word"],
    description: "Grille d'auto-evaluation apres chaque course premium. Identifiez vos forces et axes d'amelioration.",
    contentLines: [
      "Date : __ / __ / ____   Client : _____________",
      "",
      "EVALUATION (notez de 1 a 5)",
      "",
      "PONCTUALITE",
      "Arrive a l'heure : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "",
      "PROPRETE VEHICULE",
      "Exterieur impeccable : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "Interieur impeccable : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "",
      "ACCUEIL & COMMUNICATION",
      "Salutation professionnelle : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "Ouverture de porte : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "Conversation adaptee : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "",
      "CONFORT",
      "Temperature adequat : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "Conduite fluide : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "Eau/amenities disponibles : [ ]1 [ ]2 [ ]3 [ ]4 [ ]5",
      "",
      "SCORE TOTAL : ___ / 45",
      "",
      "Ce qui a bien fonctionne : _________________________",
      "A ameliorer : _________________________",
    ],
  },
  {
    id: "matrice-segmentation",
    title: "Matrice de Segmentation Clients",
    subtitle: "Identifiez vos clients les plus rentables",
    category: "GESTION CLIENTS",
    formats: ["pdf", "excel"],
    description: "Classez vos clients par valeur et frequence pour adapter votre strategie de fidelisation.",
    contentLines: [
      "CLASSIFICATION PAR VALEUR",
      "",
      "VIP (CA > 500 EUR/mois, regulier)",
      "1. _______________ CA: _____ EUR",
      "2. _______________ CA: _____ EUR",
      "3. _______________ CA: _____ EUR",
      "",
      "REGULIERS (CA 100-500 EUR/mois)",
      "1. _______________ CA: _____ EUR",
      "2. _______________ CA: _____ EUR",
      "3. _______________ CA: _____ EUR",
      "4. _______________ CA: _____ EUR",
      "5. _______________ CA: _____ EUR",
      "",
      "OCCASIONNELS (CA < 100 EUR/mois)",
      "1. _______________ CA: _____ EUR",
      "2. _______________ CA: _____ EUR",
      "",
      "PROSPECTS (pas encore clients)",
      "1. _______________ Potentiel: _____ EUR",
      "2. _______________ Potentiel: _____ EUR",
      "",
      "STRATEGIE PAR SEGMENT",
      "VIP : Attention maximale, tarif fidelite, relance proactive",
      "Reguliers : Relance mensuelle, offres ponctuelles",
      "Occasionnels : Relance trimestrielle, conversion en regulier",
      "Prospects : Prospection active, premier contact sous 48h",
    ],
  },
  {
    id: "calendrier-relance",
    title: "Calendrier de Relance Clients",
    subtitle: "Ne perdez plus jamais un client",
    category: "GESTION CLIENTS",
    formats: ["pdf", "excel"],
    description: "Planifiez vos relances mois par mois pour maintenir le lien avec vos clients et prospects.",
    contentLines: [
      "SEMAINE 1 (du __ / __ au __ / __)",
      "Lun: Relancer _______________ par ___",
      "Mar: Relancer _______________ par ___",
      "Mer: Relancer _______________ par ___",
      "Jeu: Relancer _______________ par ___",
      "Ven: Relancer _______________ par ___",
      "",
      "SEMAINE 2 (du __ / __ au __ / __)",
      "Lun: Relancer _______________ par ___",
      "Mar: Relancer _______________ par ___",
      "Mer: Relancer _______________ par ___",
      "Jeu: Relancer _______________ par ___",
      "Ven: Relancer _______________ par ___",
      "",
      "CANAUX DE RELANCE",
      "[ ] SMS personnalise",
      "[ ] Appel telephonique",
      "[ ] Email professionnel",
      "[ ] Message WhatsApp",
      "",
      "BILAN DU MOIS",
      "Clients relances : ___",
      "Courses obtenues suite aux relances : ___",
      "CA genere par les relances : _____ EUR",
    ],
  },

  // === PROSPECTION & CROISSANCE ===
  {
    id: "script-prospection",
    title: "Scripts de Prospection",
    subtitle: "Sachez exactement quoi dire",
    category: "PROSPECTION & CROISSANCE",
    formats: ["pdf", "word"],
    description: "Modeles de scripts pour prospecter par telephone, email et en personne aupres d'hotels, entreprises et restaurants.",
    contentLines: [
      "SCRIPT TELEPHONIQUE - HOTEL",
      '"Bonjour, je suis [Prenom Nom], chauffeur VTC',
      "independant installe a [Ville]. Je travaille avec",
      "plusieurs etablissements de la region pour offrir",
      "un service de transport premium a leurs clients.",
      "Je souhaiterais vous proposer un partenariat.",
      'Pourriez-vous me mettre en relation avec le',
      'concierge ou le directeur ?"',
      "",
      "SCRIPT TELEPHONIQUE - ENTREPRISE",
      '"Bonjour, je suis [Prenom Nom], je dirige une',
      "entreprise de transport prive a [Ville]. Je propose",
      "des services de deplacement professionnel avec",
      "facturation mensuelle. Puis-je presenter mon offre",
      'a votre responsable administratif ?"',
      "",
      "SCRIPT EMAIL - PRESENTATION",
      "Objet : Service de transport prive pour [Nom Hotel]",
      "",
      "Madame, Monsieur,",
      "Je me permets de vous contacter car je suis chauffeur",
      "VTC independant, specialise dans le transport premium.",
      "[Completer avec votre presentation]",
      "Cordialement, [Prenom Nom]",
      "[Telephone] | [Email]",
    ],
  },
  {
    id: "email-presentation",
    title: "Modeles d'Emails Professionnels",
    subtitle: "Communiquez avec impact",
    category: "PROSPECTION & CROISSANCE",
    formats: ["pdf", "word"],
    description: "Emails prets a l'emploi pour chaque situation : presentation, relance, remerciement, demande de recommandation.",
    contentLines: [
      "EMAIL 1 : PREMIER CONTACT",
      "Objet : Transport prive premium - Partenariat [Ville]",
      "Corps : [A personnaliser]",
      "",
      "EMAIL 2 : RELANCE (J+7)",
      "Objet : Suite a mon message - Transport prive",
      "Corps : [A personnaliser]",
      "",
      "EMAIL 3 : REMERCIEMENT POST-COURSE",
      "Objet : Merci pour votre confiance",
      "Corps : [A personnaliser]",
      "",
      "EMAIL 4 : DEMANDE DE RECOMMANDATION",
      "Objet : Un service qui pourrait interesser votre entourage",
      "Corps : [A personnaliser]",
      "",
      "EMAIL 5 : OFFRE SPECIALE FIDELITE",
      "Objet : Une attention speciale pour vous remercier",
      "Corps : [A personnaliser]",
    ],
  },
  {
    id: "plan-prospection-90j",
    title: "Plan de Prospection 90 Jours",
    subtitle: "Votre feuille de route commerciale",
    category: "PROSPECTION & CROISSANCE",
    formats: ["pdf", "excel"],
    description: "Un plan d'action semaine par semaine pour construire votre base de clients prives en 3 mois.",
    contentLines: [
      "MOIS 1 : PREPARER ET LANCER",
      "Sem 1 : Creer ses outils (carte, tarifs, email)",
      "  Actions : _________________________",
      "  Resultat : _________________________",
      "Sem 2 : Identifier 20 cibles (hotels, entreprises)",
      "  Actions : _________________________",
      "  Resultat : _________________________",
      "Sem 3 : Premiers contacts (10 appels/emails)",
      "  Actions : _________________________",
      "  Resultat : _________________________",
      "Sem 4 : Premiers rendez-vous (3 minimum)",
      "  Actions : _________________________",
      "  Resultat : _________________________",
      "",
      "MOIS 2 : ACCELERER",
      "Sem 5-8 : 15 contacts/sem, 5 RDV/sem",
      "Objectif : 3-5 premiers clients prives",
      "",
      "MOIS 3 : CONSOLIDER",
      "Sem 9-12 : Fideliser + Elargir",
      "Objectif : 8-10 clients prives actifs",
      "",
      "BILAN 90 JOURS",
      "Contacts inities : ___",
      "Clients signes : ___",
      "CA mensuel prive : _____ EUR",
    ],
  },
  {
    id: "grille-tarifaire",
    title: "Grille Tarifaire Personnalisable",
    subtitle: "Presentez vos prix avec clarte",
    category: "PROSPECTION & CROISSANCE",
    formats: ["pdf", "word"],
    description: "Une grille tarifaire professionnelle a remettre a vos clients et partenaires. A personnaliser avec vos tarifs.",
    contentLines: [
      "[VOTRE NOM / MARQUE]",
      "Service de Transport Prive Premium",
      "",
      "TARIFS DE BASE",
      "Prise en charge : _____ EUR",
      "Prix au kilometre : _____ EUR/km",
      "Prix a l'heure (mise a disposition) : _____ EUR/h",
      "Minimum de facturation : _____ EUR",
      "",
      "FORFAITS POPULAIRES",
      "Aeroport (aller simple) : _____ EUR",
      "Aeroport (aller-retour) : _____ EUR",
      "Gare (aller simple) : _____ EUR",
      "Demi-journee (4h) : _____ EUR",
      "Journee complete (8h) : _____ EUR",
      "",
      "SUPPLEMENTS",
      "Soiree (apres 20h) : +____%",
      "Week-end : +____%",
      "Jour ferie : +____%",
      "Bagage supplementaire : +_____ EUR",
      "",
      "AVANTAGES FIDELITE",
      "A partir de 5 courses/mois : -____%",
      "A partir de 10 courses/mois : -____%",
      "Contrat entreprise : Sur devis",
    ],
  },

  // === MINDSET & DEVELOPPEMENT PERSONNEL ===
  {
    id: "roadmap-12-mois",
    title: "Roadmap Personnelle 12 Mois",
    subtitle: "Votre vision annuelle d'independance",
    category: "MINDSET & DEVELOPPEMENT",
    formats: ["pdf", "excel"],
    description: "Planifiez votre transition vers l'independance trimestre par trimestre avec des objectifs clairs et mesurables.",
    contentLines: [
      "MA VISION : _________________________",
      "MON OBJECTIF A 12 MOIS : _____ EUR/mois net",
      "",
      "TRIMESTRE 1 : FONDATIONS (Mois 1-3)",
      "Objectif clients prives : ___",
      "Objectif CA prive : _____ EUR/mois",
      "Ratio prive/plateforme : ____%",
      "Actions prioritaires : _________________________",
      "Resultat : [ ] Atteint [ ] Partiellement [ ] Non atteint",
      "",
      "TRIMESTRE 2 : ACCELERATION (Mois 4-6)",
      "Objectif clients prives : ___",
      "Objectif CA prive : _____ EUR/mois",
      "Ratio prive/plateforme : ____%",
      "Actions prioritaires : _________________________",
      "Resultat : [ ] Atteint [ ] Partiellement [ ] Non atteint",
      "",
      "TRIMESTRE 3 : CONSOLIDATION (Mois 7-9)",
      "Objectif clients prives : ___",
      "Objectif CA prive : _____ EUR/mois",
      "Actions prioritaires : _________________________",
      "",
      "TRIMESTRE 4 : INDEPENDANCE (Mois 10-12)",
      "Objectif clients prives : ___",
      "Objectif CA prive : _____ EUR/mois",
      "Actions prioritaires : _________________________",
    ],
  },
  {
    id: "journal-entrepreneur",
    title: "Journal de Bord de l'Entrepreneur",
    subtitle: "Progressez chaque jour",
    category: "MINDSET & DEVELOPPEMENT",
    formats: ["pdf", "word"],
    description: "Une page quotidienne pour noter vos victoires, lecons et actions. La cle d'une progression constante.",
    contentLines: [
      "DATE : __ / __ / ____",
      "",
      "MES 3 VICTOIRES DU JOUR",
      "1. _________________________",
      "2. _________________________",
      "3. _________________________",
      "",
      "CE QUE J'AI APPRIS AUJOURD'HUI",
      "_________________________",
      "_________________________",
      "",
      "MES GRATITUDES (ce pour quoi je suis reconnaissant)",
      "1. _________________________",
      "2. _________________________",
      "3. _________________________",
      "",
      "MON DEFI DU JOUR",
      "Qu'ai-je fait qui m'a fait sortir de ma zone de confort ?",
      "_________________________",
      "",
      "BILAN FINANCIER DU JOUR",
      "Courses privees : ___ | CA prive : _____ EUR",
      "Courses plateformes : ___ | CA plateforme : _____ EUR",
      "",
      "MON ACTION PRIORITAIRE POUR DEMAIN",
      "_________________________",
    ],
  },
  {
    id: "roue-equilibre",
    title: "Roue de l'Equilibre Vie Pro/Perso",
    subtitle: "Diagnostiquez votre equilibre de vie",
    category: "MINDSET & DEVELOPPEMENT",
    formats: ["pdf"],
    description: "Un outil d'auto-diagnostic visuel pour evaluer et equilibrer les differentes dimensions de votre vie.",
    contentLines: [
      "Notez chaque domaine de 1 (insatisfait) a 10 (epanoui)",
      "",
      "SANTE PHYSIQUE : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "SANTE MENTALE & STRESS : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "FINANCES & REVENUS : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "VIE FAMILIALE & COUPLE : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "DEVELOPPEMENT PROFESSIONNEL : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "RESEAU & RELATIONS PRO : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "LOISIRS & TEMPS LIBRE : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "FORMATION & APPRENTISSAGE : ___ / 10",
      "Que faire pour ameliorer ? _________________________",
      "",
      "SCORE GLOBAL : ___ / 80",
      "TOP 3 PRIORITES D'AMELIORATION :",
      "1. _________________________",
      "2. _________________________",
      "3. _________________________",
    ],
  },
  {
    id: "croyances-limitantes",
    title: "Checklist des Croyances Limitantes",
    subtitle: "Reprogrammez votre mentalite",
    category: "MINDSET & DEVELOPPEMENT",
    formats: ["pdf", "word"],
    description: "Identifiez les pensees qui vous freinent et remplacez-les par des affirmations constructives.",
    contentLines: [
      "CROYANCE LIMITANTE --> REFORMULATION POSITIVE",
      "",
      '[ ] "Je ne suis qu\'un chauffeur"',
      '--> "Je dirige une entreprise de transport premium"',
      "",
      '[ ] "Les clients ne voudront pas payer plus cher"',
      '--> "Les clients paient pour la qualite et la fiabilite"',
      "",
      '[ ] "Je n\'ai pas le reseau pour prospecter"',
      '--> "Chaque contact est le debut d\'un reseau"',
      "",
      '[ ] "C\'est trop tard pour changer"',
      '--> "Le meilleur moment pour commencer, c\'est maintenant"',
      "",
      '[ ] "Les hotels ne travaillent qu\'avec des grosses boites"',
      '--> "Les hotels cherchent la fiabilite, pas la taille"',
      "",
      "MES PROPRES CROYANCES LIMITANTES :",
      '[ ] "________________________"',
      '--> "_________________________"',
      '[ ] "________________________"',
      '--> "_________________________"',
      '[ ] "________________________"',
      '--> "_________________________"',
    ],
  },

  // === OPERATIONNEL QUOTIDIEN ===
  {
    id: "checklist-vehicule",
    title: "Checklist Vehicule & Service",
    subtitle: "Chaque detail compte",
    category: "OPERATIONNEL",
    formats: ["pdf"],
    description: "Liste de verification quotidienne pour garantir un service impeccable a chaque course.",
    contentLines: [
      "DATE : __ / __ / ____",
      "",
      "EXTERIEUR",
      "[ ] Carrosserie propre (pas de poussiere/boue)",
      "[ ] Vitres propres (toutes)",
      "[ ] Jantes propres",
      "[ ] Pas de rayure visible",
      "[ ] Pneus en bon etat",
      "",
      "INTERIEUR",
      "[ ] Siege conducteur propre",
      "[ ] Sieges passagers impeccables",
      "[ ] Tableau de bord sans poussiere",
      "[ ] Tapis propres",
      "[ ] Pas d'odeur desagreable",
      "[ ] Parfum d'ambiance leger",
      "",
      "EQUIPEMENTS CLIENT",
      "[ ] Bouteilles d'eau fraiches (x2 minimum)",
      "[ ] Chargeur USB (Lightning + USB-C)",
      "[ ] Mouchoirs disponibles",
      "[ ] Sac de courtoisie",
      "[ ] Wi-Fi mobile operationnel",
      "",
      "TECHNIQUE",
      "[ ] Carburant > 50%",
      "[ ] GPS a jour",
      "[ ] Telephone charge a 100%",
      "[ ] Application de reservation operationnelle",
      "",
      "SCORE : ___ / 22 verifications OK",
    ],
  },
];
